<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pelanggan</name>
   <tag></tag>
   <elementGuidId>eaeea0a6-5270-469b-af58-85b83fab0c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/a[8]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(8) > div.css-ewi1jp > div.css-1xhj18k > div.css-1mqa38q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f40eb41-2099-451d-adb0-d5b4e699d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1mqa38q</value>
      <webElementGuid>aa3cb296-dea0-4379-9bd0-7b3a5386a630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelanggan</value>
      <webElementGuid>4a1fbbba-fb21-4e28-a09c-706b0c5a62e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-tnxwfz&quot;]/div[@class=&quot;chakra-stack css-owjkmg&quot;]/a[8]/div[@class=&quot;css-ewi1jp&quot;]/div[@class=&quot;css-1xhj18k&quot;]/div[@class=&quot;css-1mqa38q&quot;]</value>
      <webElementGuid>84fd025c-56a9-4537-8eda-3562e62a0841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/a[8]/div/div/div</value>
      <webElementGuid>ce5faeac-7275-4ab6-8c64-7ef616d02bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pengguna'])[1]/following::div[3]</value>
      <webElementGuid>50e8fac2-bb85-4fc7-967e-4c98dec05a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='produk'])[1]/following::div[6]</value>
      <webElementGuid>0344253b-9e03-49bb-b74d-03124838edd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- pelanggan'])[1]/preceding::div[1]</value>
      <webElementGuid>1f13d9cc-b1a4-45ea-bc00-c42021f8d46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[1]/preceding::div[5]</value>
      <webElementGuid>4f857116-c372-4635-86d4-f6f798049177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pelanggan']/parent::*</value>
      <webElementGuid>bfc2e833-f41a-49f7-86df-8dabec83c443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]/div/div/div</value>
      <webElementGuid>5e3c8cd4-37c6-4fbe-b93b-2eb3db11ed43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'pelanggan' or . = 'pelanggan')]</value>
      <webElementGuid>98930d8a-e838-46ce-90fe-f8bb1f0d7f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
